### ISSUE TITLE
Snyk Security Report

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmus#3266]
**Required Version upgrades for ChaosCenter (Frontend) :**
- [ ] Upgrade react-scripts from 3.4.4 to 4.0.0 #3209 
- [ ] Upgrade d3 from 5.16.0 to 7.0.0 #3035 
- [ ] Upgrade subscriptions-transport-ws from 0.9.17 to 0.9.19 #2870 
- [ ] Upgrade react-i18next from 11.7.2 to 11.8.10 #2655
- [ ] Upgrade @apollo/client from 3.3.11 to 3.3.12 #2654 
- [ ] Upgrade @material-ui/pickers from 3.2.10 to 3.3.10 #2653
- [ ] Upgrade yaml from 1.10.0 to 1.10.2 #2652
- [ ] Security upgrade alpine from 3.12.0 to 3 #2845
